# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/aulio_db
spring.datasource.username=postgres
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=YXVsaW8tc2VjcmV0LWtleS0yMDI0LW11eS1sYXJnYS1wYXJhLXF1ZS1zZWEtc2VndXJh
jwt.expiration=86400000

# Puerto
server.port=8080